### ISSUE TITLE
Why is mine so different from yours?

### ISSUE THREAD

**Issue by meaudotme** [bounceme/base.vim#1]
This is what mine looks like right after installing it ![before](http://s21.postimg.org/xaasofzpz/base_before.png) But then, on line 31, I changed the Normal ctermbg from 0 to 256. So now it looks like this: ![after](http://s21.postimg.org/4jdyydtw7/base_after.png) But it really doesn't look nearly as good as what I can see from [Vim Colors](http://vimcolors.com): ![Good](http://s20.postimg.org/9c03thi25/good.png)
Terminal: Sakura with 256 colors support
System: 64 bit BunsenLabs
Is something wrong?
Cheers,
Nick.

**Comment by meaudotme** [comment]
Ha! Could be the font :facepalm:
**edit:** But still, some of the colors don't match :confused:

**Comment by bounceme** [comment]
The bg color, and a few others I think, are inherited from the terminal's color scheme.
See here:
https://upload.wikimedia.org/wikipedia/en/1/15/Xterm_256color_chart.svg
the last row shows a default 16 color palette

**Comment by meaudotme** [comment]
Is there a way to make it **not** inherit any of the colors from the terminal?

**Comment by bounceme** [comment]
Of course, i'll change the few instances where I use the 0 (black) and 1(dark grey) to standard codes

**Comment by meaudotme** [comment]
Awesome, thanks mate. :+1:
